name: Rust

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: rust

    - name: Autobuild
      uses: github/codeql-action/autobuild@v3
